# Generated by Django 5.1.4 on 2024-12-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zoologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('capacidad_maxima', models.IntegerField()),
            ],
        ),
    ]
