# Generated by Django 5.1.4 on 2024-12-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0003_veterinario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veterinario',
            old_name='especialialidad',
            new_name='especialidad',
        ),
    ]
