# Generated by Django 5.1.4 on 2024-12-16 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0004_rename_especialialidad_veterinario_especialidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pruebaZoo.persona')),
                ('alimentar', models.BooleanField(default=False)),
                ('limpiar_jaula', models.BooleanField(default=False)),
                ('agregar_animal', models.BooleanField(default=False)),
                ('consultar_historial_salud', models.BooleanField(default=False)),
            ],
            bases=('pruebaZoo.persona',),
        ),
    ]
