# Generated by Django 5.1.4 on 2024-12-16 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0005_cuidador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('esta_limpia', models.BooleanField(default=True)),
                ('capacidad_verificada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_cientifico', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('estado_salud', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BUENO', 'Bueno'), ('REGULAR', 'Regular'), ('CRITICO', 'Crítico')], default='BUENO', max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('requiere_atencion_especial', models.BooleanField(default=False)),
                ('jaula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='pruebaZoo.jaula')),
            ],
            options={
                'verbose_name_plural': 'Animales',
            },
        ),
    ]
