# Generated by Django 5.1.4 on 2024-12-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0006_jaula_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaula',
            options={'ordering': ['numero_jaula']},
        ),
        migrations.AddField(
            model_name='jaula',
            name='numero_jaula',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
