# Generated by Django 5.1.4 on 2024-12-16 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0007_alter_jaula_options_jaula_numero_jaula'),
    ]

    operations = [
    ]
