# Generated by Django 5.1.4 on 2024-12-16 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0008_auto_20241216_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAlimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('HERBIVORO', 'Alimento para Herbívoros'), ('CARNIVORO', 'Alimento para Carnívoros'), ('OMNIVORO', 'Alimento para Omnívoros'), ('ESPECIAL', 'Dieta Especial')], default='ESPECIAL', max_length=20)),
                ('valor_nutritivo', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.FloatField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Alimentación Programada'), ('REALIZADA', 'Alimentación Realizada'), ('INCOMPLETA', 'Alimentación Incompleta'), ('CANCELADA', 'Alimentación Cancelada')], default='PROGRAMADA', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('alimentacion_completa', models.BooleanField(default=False)),
                ('requiere_supervision_especial', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentaciones', to='pruebaZoo.animal')),
                ('tipo_alimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pruebaZoo.tipoalimento')),
            ],
        ),
    ]
