# Generated by Django 5.1.4 on 2024-12-16 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaZoo', '0009_tipoalimento_alimentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoalimento',
            name='valor_nutritivo',
        ),
    ]
